- name: Install Samba
  apt:
    name: samba
    state: present

- name: Create share directory
  file:
    path: /srv/samba/share
    state: directory
    mode: '0775'

- name: Configure Samba
  copy:
    dest: /etc/samba/smb.conf
    content: "{{ lookup('file', 'files/smb.conf') }}"

- name: Restart Samba
  service:
    name: smbd
    state: restarted
    enabled: true
