---
- name: Install and configure public Samba share
  hosts: myhosts
  become: true

  vars:
    samba_share_name: "shared"
    samba_share_path: "/srv/samba/shared"

  tasks:
    - name: Install Samba and required packages
      apt:
        name:
          - samba
          - samba-common
          - samba-common-bin
          - smbclient
        state: present
        update_cache: true

    - name: Create public Samba share directory
      file:
        path: "{{ samba_share_path }}"
        state: directory
        mode: '0777'
        owner: nobody
        group: nogroup

    - name: Configure Samba public share
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [{{ samba_share_name }}]
          path = {{ samba_share_path }}
          browsable = yes
          writable = yes
          guest ok = yes
          guest only = yes
          read only = no
          force user = nobody

    - name: Restart smbd service
      service:
        name: smbd
        state: restarted
        enabled: true
