---
- name: Install and configure Samba
  hosts: myhosts
  become: true

  vars:
    samba_share_name: "shared"
    samba_share_path: "/srv/samba/shared"
    samba_user: "ryley"
    samba_password: "wlvreen7"  # Consider encrypting with ansible-vault

  tasks:
    - name: Install Samba and required packages
      apt:
        name:
          - samba
          - samba-common
          - samba-common-bin
          - smbclient
        state: present
        update_cache: true

    - name: Ensure smbd is enabled and started
      service:
        name: smbd
        state: started
        enabled: true

    - name: Create Samba share directory
      file:
        path: "{{ samba_share_path }}"
        state: directory
        mode: '0775'
        owner: "{{ samba_user }}"
        group: "{{ samba_user }}"

    - name: Create Samba user
      user:
        name: "{{ samba_user }}"
        shell: /sbin/nologin
        create_home: no

    - name: Set Samba password for user
      command: echo -ne "{{ samba_password }}\n{{ samba_password }}\n" | smbpasswd -a -s {{ samba_user }}
      args:
        creates: "/var/lib/samba/private/{{ samba_user }}.tdb"

    - name: Configure Samba share
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [{{ samba_share_name }}]
          path = {{ samba_share_path }}
          valid users = {{ samba_user }}
          read only = no
          browsable = yes
          guest ok = no

    - name: Restart Samba services
      service:
        name: smbd
        state: restarted
        enabled: true
