- name: Install Postfix
  apt:
    name: postfix
    state: present

- name: Configure Postfix
  copy:
    dest: /etc/postfix/main.cf
    content: "{{ lookup('file', 'files/main.cf') }}"

- name: Set mailname
  copy:
    dest: /etc/mailname
    content: "rjdcit449.local"

- name: Restart Postfix
  service:
    name: postfix
    state: restarted
    enabled: true
